---
apiVersion: v1
kind: Namespace
metadata:
  name: form
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: form
  namespace: form
spec:
  hard:
    limits.cpu: 400m
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  namespace: form
  name: limit-1
spec:
  limits:
    - type: Container
      default:
        cpu: "10m"
