apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: bob2606/hello-http:0.8.34
        name: hello-http
        env:
          - name: TEST
            value: ok
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        envFrom:
          - configMapRef:
              name: hello
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /livez
            port: 80
          periodSeconds: 10
          failureThreshold: 3
