apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        env:
          - name: STAGE
            value: K8S
          - name: JOURS
            value: "5"
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FORMATION
            valueFrom:
              configMapKeyRef:
                name: nginx
                key: SESSION
      - image: php:8.2-fpm
        name: php
