apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: Test
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: dev
        level: premium 
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        env:
          - name: STAGE
            value: Kubernetes
          - name: JOUR
            value: "4"
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: FORMATION
            valueFrom:
              configMapKeyRef:
                name: nginx
                key: SESSION
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 5
          failureThreshold: 3
      - image: php:8.2-fpm
        name: php
